repos:
  -   repo: local
      hooks:
        - id: run-pre-commit-hook-script
          name: "Run Python Script"
          entry: python3 .git/hooks/pre-commit.py
          language: system
          files: \.py$


